### ISSUE TITLE
Create Workzone Boundary Detection ROS Node

### ISSUE THREAD

**Issue by nlitz88** [nlitz88/workzone#18]
Basically, we need a ROS node that takes the OpenCV code we have written and wraps it up in a ROS node so that it can ingest 2D costmap images with bounding boxes (or whatever format the data comes in as) and spit out a 2D occupancy grid OR image (or whatever we decide on) with the workzone segmented.

Some rough ideas/requirements/notes:

- Probably fastest to implement this in Python: https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Publisher-And-Subscriber.html#writing-a-simple-publisher-and-subscriber-python, particularly because we're using OpenCV and the whole pipeline is already written in Python. Won't be blazingly fast--but it'll be lightyears faster than the BEVFusion node, so it's fine!
- If we decide our nodes our going to be sending/receiving images rather than [OccupancyGrid messages](https://docs.ros.org/en/noetic/api/nav_msgs/html/msg/OccupancyGrid.html), probably want to use the [sensor_msgs/Image message](https://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/Image.html)
- While it's not critical, as far as how to structure this: Create a new ROS package _WITHIN THIS REPOSITORY_ -- don't make the package occupy / exist as the root of the repository. Not a huge deal, just good practice :)
- I will (probably) make a second ROS meta-package later that we use to launch _all the nodes_ in the pipeline--and I will also probably create that in this repository. That'll contain a launch file to launch the nuScenes BEVFusion wrapper, the BEVFusion node itself, our workzone detection node, and then maybe something like RQT or RVIZ to visualize what's going on. UPDATE: https://github.com/nlitz88/workzone/issues/19

**Comment by CMUBOB97** [comment]
I have transferred the [boundary_generation.py](https://github.com/nlitz88/workzone/blob/complete_visualization_test/tools/workzone_cluster/boundary_generation.py) to a new [python ROS2 galactic package](https://github.com/CMUBOB97/ROS2-Boundary-Segmentation.git).

The colcon build works with boundary_node generated and a launch file working.

Here are a few things to do today (Marked as # TODO in comments, Apr 19th, Friday):
- find function calls that convert between sensor_msgs/msg/Image and np.ndarray
- rewrite display image function so that intermediate outputs will be displayed as separate topics
- test the code with BEVFusion ROS TensorRT to see if it works

tag @nlitz88 for help because my GPU is SHHHHHHHHHHHHHHHHHHHHIT!!!!!!!!!!!

**Comment by nlitz88** [comment]
> find function calls that convert between sensor_msgs/msg/Image and np.ndarray

I'm not 100% sure, but I believe this is what [cv_bridge](https://index.ros.org/p/cv_bridge/) is for. Maybe that would work?

> rewrite display image function so that intermediate outputs will be displayed as separate topics

Also, this is a great idea :100:

**Comment by nlitz88** [comment]
https://github.com/CMUBOB97/ROS2-Boundary-Segmentation

**Comment by nlitz88** [comment]
![Image](https://github.com/nlitz88/workzone/assets/9357423/63fd916f-8a3c-40ac-9e35-11cb22ef20d7)

Tada!
